class Config:
    RAW_FILE_PATH = r'C:\MB_Project\project\Myungbin-bot\data\raw\group_talk_nb.txt'
    PROCESSED_FILE_PATH = r'C:\MB_Project\project\Myungbin-bot\data\processed\group_talk_nb.txt'
    SENDER = ...
    UNIV_SENDERS = ...
    NB_SENDERS = ...
    RECEIVER = ...


cfg = Config()
